### ISSUE TITLE
XSD include error failed to load No such file or directory

### ISSUE THREAD

**Issue by viniciusbitt** [jameslan/libxml2-wasm#53]
I'm having issues when I try to create `XsdValidator` loading an .xsd that has `include` I even tried with the xsd from the `test/testfiles` folder but I was also unsuccessful.

Folder structure
![image](https://github.com/user-attachments/assets/ad7f2980-9604-40d2-99b7-5208b9dbb1e4)

```js
import fs from 'node:fs';
import { XmlDocument, XsdValidator } from 'libxml2-wasm';
import { xmlRegisterFsInputProviders } from 'libxml2-wasm/lib/nodejs.mjs';

xmlRegisterFsInputProviders()

const schemaDoc = XmlDocument.fromBuffer(fs.readFileSync('testfiles/book.xsd'), { url: 'testfiles/book.xsd' });
const validator = XsdValidator.fromDoc(schemaDoc);

validator.dispose();
schema.dispose();
```

Error:
```
file:///C:/Users/home/Documents/xml/node_modules/libxml2-wasm/lib/validates.mjs:53
        return new XmlValidateError(details.map((d) => d.message).join(''), details);
               ^

XmlValidateError: failed to load "testfiles/author.xsd": No such file or directory
Element '{http://www.w3.org/2001/XMLSchema}include': Failed to load the document 'testfiles/author.xsd' for inclusion.

    at XmlValidateError.fromDetails (file:///C:/Users/home/Documents/xml/node_modules/libxml2-wasm/lib/validates.mjs:53:16)
    at new XsdValidator (file:///C:/Users/home/Documents/xml/node_modules/libxml2-wasm/lib/validates.mjs:158:44)
    at XsdValidator.fromDoc (file:///C:/Users/home/Documents/xml/node_modules/libxml2-wasm/lib/validates.mjs:196:28)
    at file:///C:/Users/home/Documents/xml/index.mjs:8:32 {
  details: [
    {
      message: 'failed to load "testfiles/author.xsd": No such file or directory\n',
      line: 0,
      col: 0
    },
    {
      message: "Element '{http://www.w3.org/2001/XMLSchema}include': Failed to load the document 'testfiles/author.xsd' for inclusion.\n",
      line: 3,
      col: 0,
      file: 'testfiles/book.xsd'
    }
  ]
}
```

Node version: v20.12.2 (tried v23.1.0 too)

am I doing something wrong?

**Comment by jameslan** [comment]
Same issue with #51,

Please refer to the workaround in my comment.

**Comment by viniciusbitt** [comment]
@jameslan 

The workaround worked, thanks for the amazing package and for maintaining it!!
